/**
 * Cisco PSIRT openVuln API
 * The Cisco Product Security Incident Response Team (PSIRT) openVuln API is a RESTful API that allows customers to obtain Cisco Security Vulnerability information in different machine-consumable formats. APIs are important for customers because they allow their technical staff and programmers to build tools that help them do their job more effectively (in this case, to keep up with security vulnerability information). For more information about the Cisco PSIRT openVuln API visit https://developer.cisco.com/site/PSIRT/discover/overview  For detail steps on how to use the API go to:https://developer.cisco.com/site/PSIRT/get-started/getting-started.gsp  This is a beta release of a swagger YAML for the Cisco PSIRT openVuln API.  To access the API sign in with your Cisco CCO account at http://apiconsole.cisco.com and register an application to recieve a client_id and a client_secret  You can then get your token using curl or any other method you prefer.  'curl -s -k -H \"Content-Type: application/x-www-form-urlencoded\" -X POST -d \"client_id=<your_client_id>\" -d \"client_secret=<your_client_secret>\" -d \"grant_type=client_credentials\" https://cloudsso.cisco.com/as/token.oauth2'  You will receive an access token as demonstrated in the following example:  '{\"access_token\":\"I7omWtBDAieSiUX3shOxNJfuy4J6\",\"token_type\":\"Bearer\",\"expires_in\":3599}'  In Swagger, click on Change Authentication  enter the text \"I7omWtBDAieSiUX3shOxNJfuy4J6\" (which is the token you received)  then click on \"Try this operation\" 
 *
 * OpenAPI spec version: 0.0.3
 * Contact: os@cisco.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CiscoPsirtOpenVulnApi);
  }
}(this, function(expect, CiscoPsirtOpenVulnApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CiscoPsirtOpenVulnApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('securityAdvisoriesCvrfAdvisoryAdvisoryIdGet', function() {
      it('should call securityAdvisoriesCvrfAdvisoryAdvisoryIdGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfAdvisoryAdvisoryIdGet
        //instance.securityAdvisoriesCvrfAdvisoryAdvisoryIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfAllGet', function() {
      it('should call securityAdvisoriesCvrfAllGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfAllGet
        //instance.securityAdvisoriesCvrfAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfCveCveIdGet', function() {
      it('should call securityAdvisoriesCvrfCveCveIdGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfCveCveIdGet
        //instance.securityAdvisoriesCvrfCveCveIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfLatestNumberGet', function() {
      it('should call securityAdvisoriesCvrfLatestNumberGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfLatestNumberGet
        //instance.securityAdvisoriesCvrfLatestNumberGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfProductGet', function() {
      it('should call securityAdvisoriesCvrfProductGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfProductGet
        //instance.securityAdvisoriesCvrfProductGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfSeveritySeverityFirstpublishedGet', function() {
      it('should call securityAdvisoriesCvrfSeveritySeverityFirstpublishedGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfSeveritySeverityFirstpublishedGet
        //instance.securityAdvisoriesCvrfSeveritySeverityFirstpublishedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfSeveritySeverityGet', function() {
      it('should call securityAdvisoriesCvrfSeveritySeverityGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfSeveritySeverityGet
        //instance.securityAdvisoriesCvrfSeveritySeverityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfSeveritySeverityLastpublishedGet', function() {
      it('should call securityAdvisoriesCvrfSeveritySeverityLastpublishedGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfSeveritySeverityLastpublishedGet
        //instance.securityAdvisoriesCvrfSeveritySeverityLastpublishedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesCvrfYearYearGet', function() {
      it('should call securityAdvisoriesCvrfYearYearGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesCvrfYearYearGet
        //instance.securityAdvisoriesCvrfYearYearGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesIosGet', function() {
      it('should call securityAdvisoriesIosGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesIosGet
        //instance.securityAdvisoriesIosGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesIosxeGet', function() {
      it('should call securityAdvisoriesIosxeGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesIosxeGet
        //instance.securityAdvisoriesIosxeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalAdvisoryAdvisoryIdGet', function() {
      it('should call securityAdvisoriesOvalAdvisoryAdvisoryIdGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalAdvisoryAdvisoryIdGet
        //instance.securityAdvisoriesOvalAdvisoryAdvisoryIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalAllGet', function() {
      it('should call securityAdvisoriesOvalAllGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalAllGet
        //instance.securityAdvisoriesOvalAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalCveCveIdGet', function() {
      it('should call securityAdvisoriesOvalCveCveIdGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalCveCveIdGet
        //instance.securityAdvisoriesOvalCveCveIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalLatestNumberGet', function() {
      it('should call securityAdvisoriesOvalLatestNumberGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalLatestNumberGet
        //instance.securityAdvisoriesOvalLatestNumberGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalProductGet', function() {
      it('should call securityAdvisoriesOvalProductGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalProductGet
        //instance.securityAdvisoriesOvalProductGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalSeveritySeverityFirstpublishedGet', function() {
      it('should call securityAdvisoriesOvalSeveritySeverityFirstpublishedGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalSeveritySeverityFirstpublishedGet
        //instance.securityAdvisoriesOvalSeveritySeverityFirstpublishedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalSeveritySeverityGet', function() {
      it('should call securityAdvisoriesOvalSeveritySeverityGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalSeveritySeverityGet
        //instance.securityAdvisoriesOvalSeveritySeverityGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('securityAdvisoriesOvalSeveritySeverityLastpublishedGet', function() {
      it('should call securityAdvisoriesOvalSeveritySeverityLastpublishedGet successfully', function(done) {
        //uncomment below and update the code to test securityAdvisoriesOvalSeveritySeverityLastpublishedGet
        //instance.securityAdvisoriesOvalSeveritySeverityLastpublishedGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
